# Generated by Django 4.1 on 2022-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos')),
                ('photo_mod', models.ImageField(blank=True, null=None, upload_to='photos_mod')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
