# Generated by Django 4.1 on 2022-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='format',
            field=models.CharField(max_length=50),
        ),
    ]
