# Generated by Django 4.1 on 2022-08-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_photo_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=None),
        ),
    ]
